# Generated by Django 3.1.7 on 2021-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trend_grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotconfigmodel',
            name='free',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='可用货币数量', max_digits=10, null=True, verbose_name='可用数量'),
        ),
    ]
