# Generated by Django 3.1.7 on 2021-05-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trend_grid', '0002_auto_20210521_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsnoticemodel',
            options={'verbose_name': '最大购买次数通知标记', 'verbose_name_plural': '钉钉通知标记'},
        ),
    ]
