# Generated by Django 3.1.7 on 2021-12-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trend_grid', '0003_auto_20210909_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotconfigmodel',
            name='price_quantity',
            field=models.CharField(blank=True, help_text='交易金额(第一手买入1,第二手买入2...),例如:10,15,20', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='double_throw_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='补仓比率(买入价调整比率。如：设置为5,即为5%当前买入价为100，那么下次买入价为95)', max_digits=6, null=True, verbose_name='补仓比率'),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='profit_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='止盈比率(卖出价调整比率。如：设置为5,即为5%，当前买入价为100，那么下次卖出价为105)', max_digits=6, null=True, verbose_name='止盈比率'),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='quantity',
            field=models.CharField(blank=True, help_text='交易数量(第一手买入1,第二手买入2...),例如:1,2,3', max_length=256, null=True, verbose_name='交易数量'),
        ),
    ]
