# Generated by Django 3.1.7 on 2022-01-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trend_grid', '0006_auto_20220105_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='coin_type',
            field=models.CharField(help_text='交易对(如：BTC 填入 BTCUSDT/BTCBUSD)', max_length=16, verbose_name='交易对'),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='double_throw_ratio',
            field=models.CharField(blank=True, help_text='补仓比率列表(买入价调整比率。如：设置为5,即为5%当前买入价为100，那么下次买入价为95)', max_length=256, null=True, verbose_name='补仓比率'),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='price_quantity',
            field=models.CharField(help_text='交易金额列表(第一手买入1,第二手买入2...),例如:10,15,20', max_length=256, verbose_name='交易金额'),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='profit_ratio',
            field=models.CharField(blank=True, help_text='止盈比率列表(卖出价调整比率。如：设置为5,即为5%，当前买入价为100，那么下次卖出价为105)', max_length=256, null=True, verbose_name='止盈比率'),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='quantity',
            field=models.CharField(blank=True, help_text='交易数量列表', max_length=256, null=True, verbose_name='交易数量列表'),
        ),
    ]
