# Generated by Django 3.1.7 on 2022-01-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trend_grid', '0008_auto_20220106_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='current_income',
            field=models.DecimalField(decimal_places=6, default=0, help_text='当前收益', max_digits=16, verbose_name='当前收益'),
        ),
        migrations.AlterField(
            model_name='spotconfigmodel',
            name='free',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, help_text='可用货币数量', max_digits=16, null=True, verbose_name='可用数量'),
        ),
    ]
